import Head from "next/head";
import Image from "next/image";
import Menu from "./menu";
import style from "../styles/layout.module.css";
import ShoppingCart from "../components/shoppingCart";

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>HOME {title ? ` | ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <div className={style.container}>{children}</div>
      <ShoppingCart />

      <footer className={style.footer_distributed}>
        <div>
          <Image priority src="/img/logo2.png" height={144} width={344} />
        </div>
        <div>
          <p className={style.footer_links}>
            <a href="#">Home</a> ·
            <a href="/category?category=forBoys">Boys</a> ·
            <a href="/category?category=forGirls">Girls</a> ·
            <a href="/category?category=forBabies">Babies & Toddler</a> ·
            <a href="/category?category=forHome">Toys & Home</a> ·
            <a href="#">Faq</a> ·<a href="#">Contact</a>
          </p>
          <p class="footer_company_name">Kid(s)Ur © 2022</p>
          <div class="footer-icons">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fa fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fa fa-github"></i>
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
